version: '3.7'
services:
  otbasy_mysql:
    image: mysql:latest
    container_name: final-mysql-instance
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: final
      MYSQL_USER: final
      MYSQL_PASSWORD: final
      MYSQL_ROOT_PASSWORD: root  # Укажите пароль для пользователя root
    ports:
      - 3307:3306  # Порт на хосте : Порт в контейнере
    volumes:
      - mysql_data:/var/lib/mysql  # Сохранение данных между перезапусками

volumes:
  mysql_data:
